### ISSUE TITLE
No such file or directory error

### ISSUE THREAD

**Issue by TianLangStudio** [yamafaktory/jql#1]
execute jql without arguments    panic error    No such file or directory error

**Comment by TianLangStudio** [comment]
`target/debug/jql`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', libcore/result.rs:1009:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:477
   5: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:391
   6: rust_begin_unwind
             at libstd/panicking.rs:326
   7: core::panicking::panic_fmt
             at libcore/panicking.rs:77
   8: core::result::unwrap_failed
             at libcore/macros.rs:26
   9: <core::result::Result<T, E>>::unwrap
             at libcore/result.rs:808
  10: jql::utils::get_cargo_version
             at src/utils.rs:7
  11: jql::cli::get_matches
             at src/cli.rs:6
  12: jql::main
             at src/main.rs:19

**Comment by yamafaktory** [comment]
@TianLangStudio Thanks for the PR and good catch 👍. Somehow I was too quick at adding that file name... and OSX being case-insensitive is always a trap 😩.
