### ISSUE TITLE
Make `clap` an optional dependency when using jql as a library

### ISSUE THREAD

**Issue by jqnatividad** [yamafaktory/jql#113]
I'm currently using jql as a library for which `clap` (and maybe, even `colored_json`) is not required.

Can these dependencies be marked optional that are only included when perhaps a non-default `CLI` feature is used?

**Comment by yamafaktory** [comment]
Hi @jqnatividad !

You might be the first one doing that. The split between lib/bin was primarily done for testing purposes. I'll take a look at it as it might be feasible as per https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html.

**Comment by yamafaktory** [comment]
Hi @jqnatividad,

I've released a new version which should include a workaround (https://crates.io/crates/jql/3.0.6). Hope it will help!

**Comment by jqnatividad** [comment]
Hi @yamafaktory !
Thanks for the quick turn-around!
I can confirm that it works for qsv.

I just changed my cargo.toml accordingly:
`jql = { version = "3.0.6", default-features = false }`
