### ISSUE TITLE
Proposal: pre-compile selectors

### ISSUE THREAD

**Issue by osidorkin** [yamafaktory/jql#123]
I'm looking for jq like solution to be used as a library in the hot inner loop to crunch massive amount of data.
It would be nice to expose additional functions to pre-compile selectors and re-use them to get parsing out of the inner loop.

**Comment by yamafaktory** [comment]
@osidorkin the goal of `jql` is stay simple, as stated in the readme. Can you provide a concrete example of what you would like to achieve?

**Comment by osidorkin-gp** [comment]
Sure. The only public API exposed by the crate is `jql::walker` function which parses selectors on every invocation. I want to use it in the performance critical application in the hot inner loop where every CPU cycle counts. It literally crunches billions of data points per second. I'm looking for an ability to compile selectors once and run `walker` against pre-compiled selectors (Groups).

Thank you for the quick response!

**Comment by osidorkin-gp** [comment]
It can be just a few extra exports: opaque `Group` struct, `selectors_parser` function and an alternative to `walker` that takes `&[Groups]` instead of `&str` and doesn't call `selectors_parser` inside.

**Comment by yamafaktory** [comment]
@osidorkin v3.1.0 has been published to address your issues.
