### ISSUE TITLE
Conditional filters

### ISSUE THREAD

**Issue by kmaasrud** [yamafaktory/jql#135]
A feature to conditionally filter items of an array would be very useful! This would be akin to jq's [`select`](https://stedolan.github.io/jq/manual/#select(boolean_expression)) function.

My feeling is that the jql syntax is stronger than jq in it's simplicity, and thus should not adopt the "function" type signature (`select(...)`). I propose the following:

Given the below JSON

```json
[
    { "key": "give-me-this", "another-key": 42 },
    { "key": "dont-give-me-this", "another-key": 13 },
    { "key": "give-me-this", "another-key": 69 }
]
```

one could run this query:

    $ jql '.|{"key" == "give-me-this"}' file.json
    [
        { "key": "give-me-this", "another-key": 42 },
        { "key": "give-me-this", "another-key": 69 },
    ]

Inequalities would obviously be specified with `!=`. Other conditions could be supported as well, such as a way of checking if an array contains a specific element.

What do you think about this proposal? Also, thank you very much for making this amazing crate, it has been indispensable as a library in making [mdzk](https://github.com/mdzk-rs/mdzk) happen!

**Comment by yamafaktory** [comment]
Hi @kmaasrud!

Thanks for the feedback and for the kind words! Happy to hear that this crate helped you.

Regarding the proposal, I think that you've already highlighted one of the core aspect of `jql`, i.e. keeping its grammar as simple as possible. Indeed, I try to avoid adding selectors that would tend to make it more like some kind of pseudo-programming language (that's actually one of the things I don't like with `jq` - if one wants that it's presumably better to it code directly).

I'll wrap my mind around it and eventually make a PR.

Thanks again!

**Comment by kmaasrud** [comment]
Thanks for the quick response! I would guess you can come up with a more natural solution, so that sounds great :smile:

I would be happy to help, if I can contribute in any way :+1:

**Comment by yamafaktory** [comment]
Just to follow up, I've started to look at some grammar but I'm quite busy at the moment. Still keeping that on my radar.

**Comment by kmaasrud** [comment]
Thanks a lot for the followup! It's understandable that things are busy, no need to rush anything :smile:

What grammars have you been trying out?

**Comment by yamafaktory** [comment]
I think I'll probably go for something like `.|={"key":"value", "some-other-key":"some-other-value"}`

**Comment by kmaasrud** [comment]
That's neat! I agree with the combination of `|` and `=` to keep the notion that you are "filtering" something.

**Comment by yamafaktory** [comment]
Hey @kmaasrud !

A new version has been released with your feature request https://github.com/yamafaktory/jql#lens.

Thanks for the positive and constructive proposal 🚀!

**Comment by kmaasrud** [comment]
This is great @yamafaktory! Thanks for the quick feature push 🚀

If I understand the README example correctly, lenses seem to work similarly to regular filters (`"nested"|{"alpha","delta"}` would produce the same as `"nested"|={"alpha","delta"}` wouldn't it?) But they also have the added function that you can filter on values, right? Like the example you made in the comment above: `.|={"key":"value", "some-other-key":"some-other-value"}` would return objects in that array having those specific key-value pairs?

**Comment by yamafaktory** [comment]
Yes, lenses (name inspired by category theory but... not the same - this was to avoid repeating `filter`) are special filters.

If you do something like `"nested"|{"alpha","delta"}"` you're probably not going to match anything since filters only works on arrays.

My previous example was plain wrong since we just want to match keys.

To recap and to get back to your initial example, this is what you want to do:

```sh
 jql '.|={"give-me-this"}' file.json
```
Hope it's clear 🙈.

**Comment by kmaasrud** [comment]
> My previous example was plain wrong since we just want to match keys.

I think we might've misunderstood each other in that case. I would very much like to filter on key-value pairs, not just keys. Say I have an array of objects that have the fields `"firstname"` and `"lastname"`. A use-case could be to make jql return all objects that have `"lastename": "Johnson"`.

Is that possible with the current grammar?

**Comment by yamafaktory** [comment]
Indeed, this is not possible, it will only match the keys not the values.

The reasoning was that if you want to match a value, a JSON value can be anything. This is clearly not possible or we would have to limit that to primitives that are not arrays or objects (way too complicated otherwise...and maybe useless too).

While I understand the need for picking array elements by keys, I might have miss why multiple array items might have redundant key/pair values.

But nothing is set in stones 🙂. I can still go for an addition in order to get .|={"key":"value", "some-other-key":"some-other-value"}

**Comment by kmaasrud** [comment]
That sounds sensible, I must admit that I hadn't thought of that limitation - which ofc now is totally obvious 😅 Restricting it to primitives however, would be immensely useful! 

I'm sorry if my request was a bit diffuse at the start. Nonetheless, lenses are a great addition to jql that I'm very happy you have added 🎉

**Comment by yamafaktory** [comment]
@kmaasrud this time the latest release should finally match your initial request https://github.com/yamafaktory/jql#lens. I've released it as a major this time since it implies some internal changes which could potentially impact the users of the library.
