### ISSUE TITLE
Read json from stdin.

### ISSUE THREAD

**Issue by leeychee** [yamafaktory/jql#14]
jql may support read json data from `stdin`, then we can use it in a pipeline.

It's really useful.

```sh
cat example.json | jql .
```

**Comment by yamafaktory** [comment]
@leeychee Thanks a lot for the feedback 👍! I will implement that soon.

**Comment by yamafaktory** [comment]
@leeychee I've fixed it in the latest released version https://crates.io/crates/jql/2.0.0. Feel free to open a new issue if this is not addressing your issue as expected 👍.
