### ISSUE TITLE
Add binaries to releases 

### ISSUE THREAD

**Issue by patrickelectric** [yamafaktory/jql#140]
Is it possible to provide binaries to releases ?

**Comment by yamafaktory** [comment]
Hi @patrickelectric,

Which targets do you have in mind?

We can eventually give https://github.com/rust-build/rust-build.action a try.

**Comment by patrickelectric** [comment]
Hey @yamafaktory, I believe that x86-32/64 and armv7/arm64 would be great!

**Comment by yamafaktory** [comment]
Closing since @kmaasrud 's latest PR has been merged and should have addressed this issue (see https://github.com/yamafaktory/jql/releases/tag/v3.2.3).

**Comment by patrickelectric** [comment]
THATS AWESOME!
![image](https://media2.giphy.com/media/Ue0jev5l4BKgM/200w.webp?cid=ecf05e47r3w7vk0i3ta59w5lyud4jmrcld5rfpzi37iezjzc&rid=200w.webp&ct=g)
Thanks @yamafaktory and @kmaasrud
