### ISSUE TITLE
Syntax: Is it necessary to have quotes and dots as delimiters?

### ISSUE THREAD

**Issue by gerrywd** [yamafaktory/jql#151]
Looking at one of the first examples:
`jql '"primes".[0]' example.json`

My first thought was... could it have just been:
`jql 'primes[0]' example.json`

(no quotes and no period separator)

I can understand the need for the quotes around a key that contains a space or special character, but in most cases names will not have such things.

I figure you have some reasoning behind this, so I just wanted to ask as I didn't see any other issues asking this.

**Comment by yamafaktory** [comment]
Hi @gerrywd,

you can both use `jql '"primes".[0]' example.json` and `jql '"primes"[0]' example.json`.

The reasoning behind the double quotes around keys it to always make it JSON compliant (you mentioned it, those are edge cases).

See https://github.com/yamafaktory/jql/issues/56.

**Comment by gerrywd** [comment]
@yamafaktory Thank you for the explanation. Personally **from a user standpoint** it would be more readable if I didn't have to type them unless I hit one of those rare JSON files with strange keys. I'm not sure I follow the JSON compliant motive as `"primes".[0]` is not valid JSON, but perhaps you just meant the key portion being a valid JSON key. However I can understand the desire to not add more conditional logic in software. Thank you for sharing the logic, the link to the other issue that I missed and developing jql. 👍
