### ISSUE TITLE
Support TOML

### ISSUE THREAD

**Issue by suhr** [yamafaktory/jql#16]
Json is nice, but what about other formats? For example, TOML.

**Comment by yamafaktory** [comment]
Thanks for the feedback @suhr !

`jql` primarily aims at processing the JSON format and heavily relies on Serde JSON. However, since https://github.com/alexcrichton/toml-rs should provide a similar surface API, this is something that can be envisioned. First, I'd like to see `jql` maturing...

**Comment by yamafaktory** [comment]
Closing since I don't think this tool will ever target TOML.
