### ISSUE TITLE
Access children of an array without using an array index

### ISSUE THREAD

**Issue by LucioFranco** [yamafaktory/jql#18]
Hi I am trying to use `jql` to parse some elasticsearch query outputs but it seems its unable to fetch children of an array without an index.

Example:
```bash
curl localhost:9200/index/_search | jql '"hits"."hits".[]."_source"'
```
The output from the curl looks like this:
```json
{
  "hits": {
    "hits": [
      {
        "_id": "b541465c-fd6a-11e8-becd-8c859022e616",
        "_index": "index",
        "_score": 1.0,
        "_source": {
            "key": "val"
        },
        "_type": "index_type"
      }
   ]
}
```

`jql` will return the entire object in the array instead of just the `_source` field. Though when I use an index it seems to work:
```bash
curl localhost:9200/index/_search | jql '"hits"."hits".[0]."_source"'
```

Thanks, awesome library, hopefully I might have sometime to fix this.

**Comment by yamafaktory** [comment]
Side note, you can also use something like `'"hits"."hits"|"_source"'`:

```json
[
  {
    "key": "val"
  }
]
```

**Comment by LucioFranco** [comment]
@yamafaktory thanks for the insight. Why not have it set `[]` as an alias for `[0:<length of array>]`?

For the side note, I tried that and it seems to just spit out the whole object instead of filtering.

`jql ".'hits'.'hits'|'_source'"`

**Comment by yamafaktory** [comment]
Sounds like a really good approach! I'll go for that, thanks a ton 👍.

I guess your selector is not working as expected since the single/double quotes are reversed (`jql ".'hits'.'hits'|'_source'"` -> `jql '."hits"."hits"|"_source"'`)

**Comment by LucioFranco** [comment]
Ah that worked! Thanks! Yeah, I would say that syntax is a bit unclear or maybe I didn't read the readme properly 😅

**Comment by yamafaktory** [comment]
Cool, glad to hear it worked 👍.
