### ISSUE TITLE
jql 6.0.3 test failure

### ISSUE THREAD

**Issue by chenrui333** [yamafaktory/jql#208]
👋 trying to upgrade jql to the latest release, 6.0.3, but failed with the following failure

```
jql --raw-string --inline  '"cats".[2:1].[0]."third"' /private/tmp/jql-test-20230422-25743-2ghswh/example.json
Unable to parse input .[2:1].[0]."third" after Key Selector "cats"
```

While just `"cats"` as QUERY string, it works out fine

```
jql --raw-string --inline  '"cats"' /private/tmp/jql-test-20230422-25743-2ghswh/example.json
[{"first":"Pixie"},{"second":"Kitkat"},{"third":"Misty"}]
```

relates to https://github.com/Homebrew/homebrew-core/pull/129018

**Comment by yamafaktory** [comment]
Hi @chenrui333 ,

That's because I've released a major version with a lot of breaking changes which are documented in the readme.

This is how you should do the query now: `'"cats"[2:1][0]"third"'`. Basically the tokens have been simplified in the grammar, the dots are not necessary.

Please let me know if that doesn't work as expected.

**Comment by yamafaktory** [comment]
By the way, I've just realized that you are a Homebrew maintainer 😄 ! Thanks for your work!

Second thing, the release is incorrect. That's a minor thing but it should be `
jql-v6.0.3-aarch64-apple-darwin.zip ` not `
jql-jql-v6.0.3-aarch64-apple-darwin.zip `.

**Comment by yamafaktory** [comment]
Actually found a bug, will fix :).

**Comment by yamafaktory** [comment]
@chenrui333 a new patch version has been released with the fix and the correct name :). Please let me know if you have any issue.

N.B.: I will update the readme with some more complete / cookbook examples since the queries are different compared to v5.

**Comment by chenrui333** [comment]
Worked for us, thanks @yamafaktory!
