### ISSUE TITLE
Migration guide for library users?

### ISSUE THREAD

**Issue by jqnatividad** [yamafaktory/jql#211]
Hi @yamafaktory ,
Amazing stuff with the 6.x release!

Any chance of a migration guide for library users?

If not, any tips would be most appreciated!

**Comment by yamafaktory** [comment]
Hi @jqnatividad ,

Thanks for the feedback! It was definitely necessary to clean-up the code and to address some legacy design decisions (https://github.com/yamafaktory/jql/discussions/205).

You might have noticed that the project is now a workspace with 3 crates (binary + 2 libraries). This is definitely a good point, I'll update the readme to expose the docs for both libraries (https://docs.rs/jql-parser/6.0.4/jql_parser/ + https://docs.rs/jql-runner/6.0.4/jql_runner/).

In your case, you might be looking for the `token` runner https://docs.rs/jql-runner/6.0.4/jql_runner/runner/fn.token.html and the tokens https://docs.rs/jql-parser/6.0.4/jql_parser/tokens/enum.Token.html .

What is definitely breaking for you:
- **Groups** are now separated using the `GroupSeparator`
- **Filters** are gone and replaced by the `PipeInOperator` and the `PipeOutOperator`

Lenses are mostly similar but you can extend the query after them without getting weird results (v5 was definitely not made to handle that properly).

## Pipes

The pipe (in / out) operators simplify the way you can parallelize a selection within a query. This is - like filters - an array-only processing. Here I'm taking the simple example from the readme:

**JSON input**

```json
{ "a": [{ "b": { "c": 1 } }, { "b": { "c": 2 } }] }
```

**Query**

```sh
'"a"|>"b""c"<|[1]'
```

**JSON output**

```json
2
```

Let's decompose the **query**:

`"a"` → `|>` → `"b"` → `"c"` → `<|` → `[1]`

`KeySelector("a")` → `PipeInOperator` → `KeySelector("b")` → `KeySelector("c")` → `PipeOutOperator` → `ArrayIndexSelector(Vec<Index(1)>)`

What happens is that when the runner reaches the `PipeInOperator`, the next tokens are then applied in parallel on each item of the array (https://github.com/yamafaktory/jql/blob/a438ab0039faf64c3329fb09bae399ae95601000/crates/jql-runner/src/runner.rs#L94 - using `rayon` so we get some major benefit with the pool of worker threads). 

The `PipeOutOperator` is then used to tell the runner *"please stop parallelizing"*, I want to apply the next tokens to the entirety of the current data. 

Going through all the steps:

```json
{ "a": [{ "b": { "c": 1 } }, { "b": { "c": 2 } }] }
```

⬇️

```json
[{ "b": { "c": 1 } }, { "b": { "c": 2 } }]
```

⬇️

`PipeInOperator` (no transformation | internal flag for the runner to start the parallelization)

⬇️

```json
[{ "b": { "c": 1 } }, { "b": { "c": 2 } }]
```

⬇️

```json
[{ "c": 1 }, { "c": 2 }]
```

⬇️

```json
[1, 2]
```

⬇️

`PipeOutOperator` (end of parallelization)

⬇️

```json
[1, 2]
```

⬇️

```json
2
```

Please let me know if something else is not clear 😄 .

**Comment by jqnatividad** [comment]
Whoa!

I asked for a quick tip, and I got a personalized mini-migration guide! 💯 😄 

Thanks sooo much for this detailed explanation, will try to upgrade qsv to use the new library and I'll let you know!

**Comment by jqnatividad** [comment]
Hi @yamafaktory ,
Managed to upgrade to 6 over the weekend, going for a simpler jql-runner crate.

In a future pass, I hope to cache the parsed selector (is it the same as tokens) instead of running a raw jql query for every iteration in a hot loop.
