### ISSUE TITLE
Windows release artifacts fail to upload since v5.1.3

### ISSUE THREAD

**Issue by aliesbelik** [yamafaktory/jql#217]
The release builds are no longer including the pre-built binaries for Windows (since v5.1.3) due to a breaking change in the [softprops/action-gh-release](https://github.com/softprops/action-gh-release) github action used.

```
Release

  Run softprops/action-gh-release@v1
    with:
      files: D:\a\jql\jql\jql-v5.1.3-x86_64-pc-windows-msvc.zip
    D:\a\jql\jql\jql-v5.1.3-x86_64-pc-windows-msvc.zip.sha256
    
      token: ***
    env:
      ASSET_PATH: D:\a\jql\jql\jql-v5.1.3-x86_64-pc-windows-msvc.zip
      CHECKSUM_PATH: D:\a\jql\jql\jql-v5.1.3-x86_64-pc-windows-msvc.zip.sha256
      GITHUB_TOKEN: ***
  🤔 Pattern 'D:\a\jql\jql\jql-v5.1.3-x86_64-pc-windows-msvc.zip' does not match any files.
  🤔 Pattern 'D:\a\jql\jql\jql-v5.1.3-x86_64-pc-windows-msvc.zip.sha256' does not match any files.
  🤔 D:\a\jql\jql\jql-v5.1.3-x86_64-pc-windows-msvc.zip,D:\a\jql\jql\jql-v5.1.3-x86_64-pc-windows-msvc.zip.sha256 not include valid file.
  🎉 Release ready at https://github.com/yamafaktory/jql/releases/tag/v5.1.3
```
([full release workflow log](https://github.com/yamafaktory/jql/actions/runs/4786330257/jobs/8510147539))

Sometime mid November, [softprops/action-gh-release@v1](https://github.com/softprops/action-gh-release) updated the node-glob dependency to 8.0, which [changed](https://github.com/isaacs/node-glob/blob/main/changelog.md#80) the behavior of `\` to only be an escape character rather than a path separator.

More info here:
https://github.com/softprops/action-gh-release/issues/280

I've tried 2 different workarounds to fix Windows binaries:

1. pin version of softprops/action-gh-release to v0.1.13 instead of v1:
  ```
    uses: softprops/action-gh-release@v0.1.13
  ```
until original issue will be fixed;
([tested here](https://github.com/aliesbelik/jql/actions/runs/4866361655/jobs/8678008824))

2. [switch to forward slashes](https://github.com/yamafaktory/jql/commit/f7449498ade08c3de3161d144d6ea5a60eae59c3) in PATH-variables in Windows case:
```
Run softprops/action-gh-release@v1
  with:
    files: D:/a/jql/jql/jql-v6.0.7-x86_64-pc-windows-msvc.zip
  D:/a/jql/jql/jql-v6.0.7-x86_64-pc-windows-msvc.zip.sha256
  
    token: ***
  env:
    ASSET_PATH: D:/a/jql/jql/jql-v6.0.7-x86_64-pc-windows-msvc.zip
    CHECKSUM_PATH: D:/a/jql/jql/jql-v6.0.7-x86_64-pc-windows-msvc.zip.sha256
    GITHUB_TOKEN: ***
⬆️ Uploading jql-v6.0.7-x86_64-pc-windows-msvc.zip...
⬆️ Uploading jql-v6.0.7-x86_64-pc-windows-msvc.zip.sha256...
🎉 Release ready at https://github.com/aliesbelik/jql/releases/tag/jql-v6.0.7
```
([tested here](https://github.com/aliesbelik/jql/actions/runs/4867208765/jobs/8679564013))

and both completed successfully.

Just in case you are not planning to discount Windows binary option.  :fearful:

**Comment by yamafaktory** [comment]
@aliesbelik thanks for tte feedback !

I definitely don't want to stop supporting Windows - even though I'm not using it.

The second approach looks good to me, would you mind creating a PR?

**Comment by aliesbelik** [comment]
Sure, happy to contribute.
