### ISSUE TITLE
Allow streaming by line

### ISSUE THREAD

**Issue by lewisdiamond** [yamafaktory/jql#26]
File a:
```
{"a":1, "b":2}
{"a":3, "b":4}
{"a":5, "b":6}
```
`< a jql '.'`
Currently says `Invalid JSON file or content`

It should take every line as a record and run the query (as with jq).

**Comment by yamafaktory** [comment]
@lewisdiamond Thanks for your feedback, I'll have a look at it. Streaming like https://stedolan.github.io/jq/manual/#Streaming is also something I have in mind.

**Comment by yamafaktory** [comment]
@lewisdiamond the latest version should address your issue https://crates.io/crates/jql/2.4.0.
