### ISSUE TITLE
Regex/ranges matching

### ISSUE THREAD

**Issue by Wicpar** [yamafaktory/jql#265]
Hi,

I was wondering if you would accept improvements regarding the use of regex expressions for matching/filtering and further operators like the ability to sort/dedup arrays.

I am looking for a library able to transform datasets, i.e. a key value list where the key is a string representing concatenated data `{YYYY}{code}{section}` -> Name  and the ability to extract the years, codes, and sections into deduplicated sorted lists in order to use them in selects for filters.

**Comment by yamafaktory** [comment]
Hi @Wicpar ,

I tend to keep the surface API as small as possible for this tool. The goal is to keep it lightweight, performant and user-friendly. Oftentimes when something needs quite a lot of processing, I'd argue that this should be handled by a specific piece of code. Though I'm always open to discussion of course :).

I can see a value in adding a way to dedup arrays for primitive values only. Regarding sorting, it's already a bit more opinionated: letters first, number first, etc.

Regarding regex, this could be achieved by using the `regex` crate and then allow for key selection based on it. However, I'd definitely not introduce some kind of extraction mechanism based on regex matches. This is clearly out of the scope of this tool (and I'm sure there are alternative ones).

**Comment by Wicpar** [comment]
Alright, thanks !
I'll look to either fork or an alternative then.
The usecase needs to allow users to program extractors so extra custom code is not possible.

**Comment by Wicpar** [comment]
Thanks, this looks like what i need !
