### ISSUE TITLE
Getting the keys

### ISSUE THREAD

**Issue by sabarish-vm** [yamafaktory/jql#282]
Hi,

Thank you for the nice tool. I am wondering if it is possible to extract all the keys in the json file.
That is an equivalent to "jq keys < file.json" https://jqlang.github.io/jq/manual/#keys-keys_unsorted.

**Comment by yamafaktory** [comment]
Hi @sabarish-vm ,

I was busy lately - I'll have a look :)

**Comment by yamafaktory** [comment]
Hi @sabarish-vm ,

A new version has been released with a new operator (not a flag as jq) -> https://github.com/yamafaktory/jql?tab=readme-ov-file#keys-operator

**Comment by sabarish-vm** [comment]
Hi @yamafaktory, 

Thanks a lot 🥳
