### ISSUE TITLE
Add LICENSE files

### ISSUE THREAD

**Issue by ignatenkobrain** [yamafaktory/jql#30]
It would be very useful since that there are tens of different variations of MIT licenses.

I would appreciate if you could publish new version after that.

**Comment by yamafaktory** [comment]
Hi @ignatenkobrain,
Sorry I completely missed your comment...
Will fix that and keeps you updated!

**Comment by yamafaktory** [comment]
@ignatenkobrain https://crates.io/crates/jql/2.4.6 has been published.
