### ISSUE TITLE
Arch Linux AUR package

### ISSUE THREAD

**Issue by frol** [yamafaktory/jql#41]
I created AUR package for Arch Linux: https://aur.archlinux.org/packages/jql/

The installation instructions for Arch Linux users:

```
yay -S jql
```

**Describe the solution you'd like**

I suggest adding this (as installation instructions or just a mention of the link) to the README

**Comment by yamafaktory** [comment]
Hi @frol ! 

This is just awesome, thanks a ton! 

I'll do it ASAP! :bowing_man:

**Comment by yamafaktory** [comment]
@frol Thanks a lot for your contribution! A new release has been created.
