### ISSUE TITLE
State the performance

### ISSUE THREAD

**Issue by tacone** [yamafaktory/jql#43]
I suggest you to state whether jql is fast or not, and if the throughput is one of the goals of the project. As simple as it sounds, it may drive adoption.

Publishing benchmarks result may also help.

Good luck!

**Comment by dufferzafar** [comment]
And perhaps a comparison (performance & feature set) with jq? : https://github.com/stedolan/jq/

**Comment by yamafaktory** [comment]
Thanks for the feedback!

At the moment, `jql` uses benchmarks internally as regression tests. You can see it in the Github Actions under the `bench` step, like here e.g. https://github.com/yamafaktory/jql/actions/runs/116121477.

I've never compared the performance against `jq` e.g. For sure, this is doable.

Regarding the feature set comparison, what would you expect? I don't have a deep knowledge of `jq`. It's clear that `jq` provides way more features than this tool but IMHO at the cost of being somehow bloated. I'm not sure if comparing both is fair as the objectives are quite different.

**Comment by yamafaktory** [comment]
A little update: I still don't know which feature(s) should have benchmarks or not and where to put that (maybe a link to another doc like BENCHMARKS.md). For example, `jql` uses `rayon` internally (https://github.com/rayon-rs/rayon/blob/master/FAQ.md) which makes it multi-threaded.

Given the following simple JSON nested arrays, let's say e.g. you want to flatten it (took the example from https://stedolan.github.io/jq/manual/#flatten,flatten(depth)):
```json
[1, [2], [[3]]]
```
### jq
```sh
echo '[1, [2], [[3]]]' | jq 'flatten' 
[
  1,
  2,
  3
]

time bash -c 'for i in `seq 1 1000` ; do echo '"'"'[1, [2], [[3]]]'"'"' | jq 'flatten' > /dev/null ; done'
bash -c   24.85s user 0.86s system 100% cpu 25.451 total
```
### jql
```sh
echo '[1, [2], [[3]]]' | jql '...'           
[
  1,
  2,
  3
]

time bash -c 'for i in `seq 1 1000` ; do echo '"'"'[1, [2], [[3]]]'"'"' | jql '...' > /dev/null ; done'
bash -c   2.56s user 1.08s system 235% cpu 1.542 total
```

**Comment by yamafaktory** [comment]
I'll probably have a look at https://github.com/sharkdp/hyperfine and use it whenever I'll some spare time.

**Comment by yamafaktory** [comment]
Some basic comparison benchmarks are now available here https://github.com/yamafaktory/jql/blob/master/PERFORMANCE.md (triggered every night).

I'll try to add more of them.

Closing for now.
