### ISSUE TITLE
crates.io calls the license "non-standard"

### ISSUE THREAD

**Issue by cuviper** [yamafaktory/jql#49]
FYI, using `license-file` without `license` leads to crates.io listing this crate as having a "non-standard" license, even though it's really just MIT. See also rust-lang/cargo#8537.

**Comment by yamafaktory** [comment]
Hi and thanks for the info!
I'll fix it after my vacation🏖!

**Comment by yamafaktory** [comment]
A new version has been released https://crates.io/crates/jql/2.6.6.

Thanks again for the heads up!
