### ISSUE TITLE
Add support for raw-output.

### ISSUE THREAD

**Issue by krupatil** [yamafaktory/jql#50]
Is there any plan to add support for raw input and raw-output? That will be really helpful to use this for CLI usage.

Example for how `jq` provides this:
```bash
$ echo '{"foo": "bar"}' | jq '.foo'
"bar"

$ echo '{"foo": "bar"}' | jq -r '.foo'
bar
```

**Comment by yamafaktory** [comment]
Hi @krupatil and thanks for the input! 

Implementing a raw output flag seems pretty straightforward as Serde has a feature for that https://docs.serde.rs/serde_json/value/struct.RawValue.html. I'll have a look at it. 

What do you mean by raw input? Isn't already covered by https://docs.serde.rs/serde_json/value/struct.RawValue.html?

**Comment by yamafaktory** [comment]
@krupatil I've checked the `raw-output` flag from `jq` here https://stedolan.github.io/jq/manual/:
> With this option, if the filter's result is a string then it will be written directly to standard output rather than being formatted as a JSON string with quotes. This can be useful for making jq filters talk to non-JSON-based systems.

I've implemented the same flag/behavior in `jql` (`-r` or `--raw-output`): it will only drop JSON double-quotes on a string selection - the other primitives will work out of the box (and the output for complex objects will stay the same).

The documentation has been updated [here](https://github.com/yamafaktory/jql#raw-output).

A new version has been released https://crates.io/crates/jql/2.7.0 :rocket:.

Thanks again for the request :+1: !

**Comment by krupatil** [comment]
Awesome! Thank you @yamafaktory for accepting the request.

**Comment by yamafaktory** [comment]
@krupatil thanks for requesting it :bow: !
