### ISSUE TITLE
An example of working with arrays in the docs?

### ISSUE THREAD

**Issue by keblek** [yamafaktory/jql#57]
The readme for this project is quite good and I've been been very productive with it so far.

However, I'm having problems getting jql to print only the values. The closest I can get is screened below. 

My question is, how does one start by selecting all the objects in an array then filtering out by keys, then displaying the children?

I haven't been able to figure it out from looking at the docs.
[
  {
    "txid": "15a10e97de1dca95dfeb3d8d06dac87dbb494eab8acc00abca0f96c140b97a73",
    "vout": 0,
    "address": "tb1qd2cvqk30f8kw3hj53wlj053dd9amnhhefg02gx",
    "label": "",
    "scriptPubKey": "00146ab0c05a2f49ece8de548bbf27d22d697bb9def9",
    "amount": 0.001,
    "confirmations": 61,
    "spendable": true,
    "solvable": true,
    "desc": "wpkh([b9a5ac96/0'/0'/2']03d94b78001ec7bdfffe41cca947e77219342272bb62946af779311358f835e57f)#3e78xplt",
    "safe": true
  },
  {
    "txid": "393e1b08b7d2afd21f41f23025f5d79a06a7d12bc95a598de8b3c2f0340293a0",
    "vout": 1,
    "address": "tb1qd2cvqk30f8kw3hj53wlj053dd9amnhhefg02gx",
    "label": "",
    "scriptPubKey": "00146ab0c05a2f49ece8de548bbf27d22d697bb9def9",
    "amount": 0.001,
    "confirmations": 61,
    "spendable": true,
    "solvable": true,
    "desc": "wpkh([b9a5ac96/0'/0'/2']03d94b78001ec7bdfffe41cca947e77219342272bb62946af779311358f835e57f)#3e78xplt",
    "safe": true
  },
  {
    "txid": "faa64c516c90302c624c7f7ffc26366376ac12813b1cc6e4eb8a192e3e0f08e4",
    "vout": 0,
    "address": "tb1qtlefx6f36vyx4l4g2wyvas4ghyuynn46xptyya",
    "label": "",
    "scriptPubKey": "00145ff2936931d3086afea85388cec2a8b93849ceba",
    "amount": 0.0022,
    "confirmations": 61,
    "spendable": true,
    "solvable": true,
    "desc": "wpkh([b9a5ac96/0'/0'/1']03a430c19febf6d59786fe600ff185e2e8c4efa81212ead8f5a741a9427090e766)#9lt0k576",
    "safe": true
  }
]

Final Goal;
$ bt listunspent | jql -r 'something something something'
15a10e97de1dca95dfeb3d8d06dac87dbb494eab8acc00abca0f96c140b97a73
0
0.001
393e1b08b7d2afd21f41f23025f5d79a06a7d12bc95a598de8b3c2f0340293a0
1
0.001
faa64c516c90302c624c7f7ffc26366376ac12813b1cc6e4eb8a192e3e0f08e4
0
0.0022

<img width="1792" alt="selecting arrays" src="https://user-images.githubusercontent.com/68111648/90318014-ab60ed80-df2d-11ea-99c6-4ca4a29c0e5f.png">

**Comment by yamafaktory** [comment]
Hi @keblek.

What you're trying to achieve is currently not possible. The raw `-r` flag was recently introduced and only works with String primitives (it mimics what `jq` also does). There's no way for `jq` to know how to cast an Object like:

```json
{
  "txid": "15a10e97de1dca95dfeb3d8d06dac87dbb494eab8acc00abca0f96c140b97a73",
  "vout": 0,
  "amount": 0.001
}
```
to
```sh
15a10e97de1dca95dfeb3d8d06dac87dbb494eab8acc00abca0f96c140b97a73
0
0.001
```
because why should it iterate over an object and return three lines of String? `jql` is meant to take JSON in and output JSON back (the `-r` flag is already quite out of scope IMHO).

So in your example `jql '.|{"txid","vout","amount"}'` is enough to get:
```json
[
  {
    "txid": "15a10e97de1dca95dfeb3d8d06dac87dbb494eab8acc00abca0f96c140b97a73",
    "vout": 0,
    "amount": 0.001
  },
  {
    "txid": "393e1b08b7d2afd21f41f23025f5d79a06a7d12bc95a598de8b3c2f0340293a0",
    "vout": 1,
    "amount": 0.001
  },
  {
    "txid": "faa64c516c90302c624c7f7ffc26366376ac12813b1cc6e4eb8a192e3e0f08e4",
    "vout": 0,
    "amount": 0.0022
  }
]

You can get an array of `amount` with `jql -r '.|{"txid","vout","amount"}|"amount"'` e.g.
```

**Comment by keblek** [comment]
Thank you very much for replying. I have found a different way to get to where I wanted and have realised that my original way of doing things would have resulted in an overly complicated jql expression (even if it were supported - which its not). The last tip is helpful so this can be closed.

**Comment by keblek** [comment]
If jql is only meant to input/output json, perhaps you can give a recommendation on how best to strip out the json brackets and keys to get the raw data. 

grep or sed?

**Comment by yamafaktory** [comment]
@keblek Did you reopen intentionally?

**Comment by yamafaktory** [comment]
@keblek oh sorry, we both sent our messages at the same time.

What are you doing now - as a command ?

**Comment by keblek** [comment]
Sorry for the confusion, I just had a small after thought. I don't mean to monopolise your time. 

What I am trying to do is too complicated and is better done by doing multiple commands rather than one shell command, otherwise I am having to write a crazy regex expression. Again sorry about the confusion.

**Comment by yamafaktory** [comment]
@keblek no worries! Feel free to open an issue if something doesn't work as expected.
