### ISSUE TITLE
'sdf' postfix in error is intentional?

### ISSUE THREAD

**Issue by HenkPoley** [yamafaktory/jql#62]
Here: https://github.com/yamafaktory/jql/blob/8f4ac685f092aacbe6c9a6f101753bcdcb8244a4/src/bin.rs#L49-L50

**Comment by yamafaktory** [comment]
Hi @HenkPoley.

Not at all... This was accidentally introduced here https://github.com/yamafaktory/jql/commit/8f4ac685f092aacbe6c9a6f101753bcdcb8244a4

**Comment by yamafaktory** [comment]
@HenkPoley A new release has been publish (it will also address the performance issue you mentioned - this is auto-generated as a GitHub Action workflow, so I'll merge it afterwards)
