### ISSUE TITLE
README example doesn't return the same output

### ISSUE THREAD

**Issue by yurivict** [yamafaktory/jql#73]
> jql '"laptops".[1:0]|"laptop"|"brand","laptops"|"laptop"|"brand"' example.json

returns
```
[
  [
    "Asus",
    "Apple"
  ],
  [
    "Apple",
    "Asus"
  ]
]
```
while README says that it should return
```
[
  "Apple",
  "Asus"
]
```

**Comment by yamafaktory** [comment]
@yurivict thanks for the feedback! Indeed this command is definitely not returning what the readme mentioned... Probably a mistake (bad copy & paste) I did quite a long time ago...

Basically:

```sh
jql '"laptops".[1:0]|"laptop"|"brand"' example.json
```

Returns:

```json
[
  "Asus",
  "Apple"
]
```

So using two groups as follow:

```sh
jql '"laptops".[1:0]|"laptop"|"brand","laptops"|"laptop"|"brand"' example.json
```

Will return an array combining both groups:

```json
[
  [
    "Asus",
    "Apple"
  ],
  [
    "Apple",
    "Asus"
  ]
]
```

**Comment by yamafaktory** [comment]
@yurivict A new version has been released to address the issue https://crates.io/crates/jql/2.8.1. Thanks again for your feedback :+1: !
