### ISSUE TITLE
Benchmark and query question

### ISSUE THREAD

**Issue by Th3Whit3Wolf** [yamafaktory/jql#78]
I edited the `performance.sh` with a benchmark to test jql an jq with a large, approximately 5.9 MB, json file (First 1000 Microsoft repos on github).

```shell
#!/usr/bin/env bash

REPORT=$(pwd)/PERFORMANCE.md
PERFORMANCE_TMP_DIR=$(pwd)/performance_tmp
MD_FILES="$PERFORMANCE_TMP_DIR/"*".md"
MIN_RUNS=1000
JSON=$(pwd)/ms.json
JSON_TMP=$(pwd)/tmp.json

# Remove export file if present.
rm -f $REPORT

# Create the directory.
mkdir $PERFORMANCE_TMP_DIR

# Get a large json file
if [ ! -f $JSON ]; then
    for PG in {1..10}; do
        echo -ne "\rGettings microsoft github repos ... ${PG}0% "
        curl -S -s -H "Accept: application/vnd.github.v3+json" \
        https://api.github.com/orgs/microsoft/repos?per_page=100\&page=$PG \
        -o $JSON_TMP
        cat $JSON_TMP >> $JSON 
        rm $JSON_TMP
    done
    echo -e "\nms.json is $(du -h ${JSON} | | awk '{print $1}')"
fi

Bench1="'{\"foo\": \"bar\"}'"
Bench2="'[1, 2, 3]'"
Bench3="'[1, [2], [[3]]]'"

# Run the benchmarks.
hyperfine \
    --export-markdown "$PERFORMANCE_TMP_DIR/OBJECT.md" \
    --min-runs $MIN_RUNS \
    "echo $Bench1 | jq '.foo'" \
    "echo $Bench1 | jql '.\"foo\"'"

hyperfine \
    --export-markdown "$PERFORMANCE_TMP_DIR/ARRAY_INDEX.md" \
    --min-runs $MIN_RUNS \
    "echo $Bench2 | jq '.[0]'" \
    "echo $Bench2 | jql '.[0]'"

hyperfine \
    --export-markdown "$PERFORMANCE_TMP_DIR/ARRAY_FLATTEN.md" \
    --min-runs $MIN_RUNS \
    "echo $Bench3 | jq 'flatten'" \
    "echo $Bench3 | jql '...'"

hyperfine \
    --export-markdown "$PERFORMANCE_TMP_DIR/LARGE_JSON.md" \
    --min-runs $MIN_RUNS \
    "cat $JSON | jq -r '.[] | .name, .url, .language, .stargazers_count, .watchers_count'" \
    "cat $JSON | jql '.|{\"name\",\"url\", \"language\", \"stargazers_count\", \"watchers_count\"}'"

# Merge all the markdown files into the performance one.
for md_file in $MD_FILES; do (cat "${md_file}"; echo) >> $REPORT; done

# Remove the directory.
rm -R -f $PERFORMANCE_TMP_DIR
```

| Command | Mean [ms] | Min [ms] | Max [ms] | Relative |
|:---|---:|---:|---:|---:|
| `cat /home/doc/Code/Bench/ms.json \| jq -r '.[] \| .name, .url, .language, .stargazers_count, .watchers_count'` | 104.0 ± 9.8 | 89.2 | 121.3 | 1.00 |
| `cat /home/doc/Code/Bench/ms.json \| jql '.\|{"name","url", "language", "stargazers_count", "watchers_count"}'` | 2317.6 ± 178.6 | 1801.3 | 2653.9 | 22.29 ± 2.71 |

jql ended up being much slower so I figure I probably did something wrong. How can I make this a fairer comparison?

**Comment by yamafaktory** [comment]
Hi @Th3Whit3Wolf and thanks for taking the time to play a bit more with those benchmarks!

I run you script and only kept the Github bench and I'm not getting such high numbers for jql, maybe something went wrong on your machine or hyperfine did something inconsistent?

```sh
./performance.sh 
Gettings microsoft github repos ... 100% ./performance.sh: command substitution: line 27: syntax error near unexpected token `|'
./performance.sh: command substitution: line 27: `du -h ${JSON} | | awk '{print $1}')"'
Benchmark #1: cat /home/yamafaktory/Dev/jql/ms.json | jq -r '.[] | .name, .url, .language, .stargazers_count, .watchers_count'
  Time (mean ± σ):     111.4 ms ±   4.9 ms    [User: 111.0 ms, System: 6.0 ms]
  Range (min … max):   105.1 ms … 148.3 ms    1000 runs
 
  Warning: The first benchmarking run for this command was significantly slower than the rest (143.6 ms). This could be caused by (filesystem) caches that were not filled until after the first run. You should consider using the '--warmup' option to fill those caches before the actual benchmark. Alternatively, use the '--prepare' option to clear the caches before each timing run.
 
Benchmark #2: cat /home/yamafaktory/Dev/jql/ms.json | jql '.|{"name","url", "language", "stargazers_count", "watchers_count"}'
  Time (mean ± σ):     101.4 ms ±  10.4 ms    [User: 164.2 ms, System: 24.6 ms]
  Range (min … max):    91.2 ms … 188.4 ms    1000 runs
 
  Warning: Statistical outliers were detected. Consider re-running this benchmark on a quiet PC without any interferences from other programs. It might help to use the '--warmup' or '--prepare' options.
 
Summary
  'cat /home/yamafaktory/Dev/jql/ms.json | jql '.|{"name","url", "language", "stargazers_count", "watchers_count"}'' ran
    1.10 ± 0.12 times faster than 'cat /home/yamafaktory/Dev/jql/ms.json | jq -r '.[] | .name, .url, .language, .stargazers_count, .watchers_count''
```

**Comment by yamafaktory** [comment]
If you want, and to be more fair, we can update the performance script according to your changes in this repo (will have to adjust a few things) and see how it behaves in the Github CI.

**Comment by Th3Whit3Wolf** [comment]
The benchmarks are very consistent on my machine, but this machine has been acting weird the last couple days (nothing I think would affect performance though). I'll try testing on another machine.

It would be cool to see this on your benchmarks! It should be noted however that github's api limits requests from unauthenticated clients to 60 per hour. I don't know how that work's with github actions being test on multiple machines. For best results though it may work out better to upload a large json file rather than make it dynamically.

**Comment by yamafaktory** [comment]
Thanks for the feedback.
The file can be stored directly in this repository. I'll try to find some time today to make a new release (the performance is tracked on new releases only).

**Comment by yamafaktory** [comment]
@Th3Whit3Wolf I've just released a new version. The Ci has been triggered here and the bench file is going to be updated. I'll merge it afterwards. https://github.com/yamafaktory/jql/runs/1604707877?check_suite_focus=true

**Comment by yamafaktory** [comment]
Of course, feel free to reopen it! Let's see how it's going to behave...

**Comment by yamafaktory** [comment]
Interestingly, it took almost one and half hour to run the bench... Of course Github CI virtual servers are not monster machines https://docs.github.com/en/free-pro-team@latest/actions/reference/specifications-for-github-hosted-runners#supported-runners-and-hardware-resources. But this is somehow a crazy amount of time and also confirming what you faced. I don't know yet why this is taking so long to perform the task. jql uses serde and rayon, so globally it's fast and even faster than jq. But here this looks like it's exponentially slower. Will try to investigate by disabling the parallelization.

**Comment by yamafaktory** [comment]
Ok, basically there are two things that are wrong:
1. the jq command doesn't return valid JSON but something simpler, hence the faster timing
2. what takes forever - and that's the same for jq with a similar command - is displaying everything to stdout

Will fix that in another release with some other improvements.

**Comment by Th3Whit3Wolf** [comment]
Is there a jq equivalent of this command that returns valid json?

**Comment by yamafaktory** [comment]
Yes for sure, I have it in a feature branch and will soon create a PR. Also figured out an issue with piping to `stdin` which is making jql slow as hell on big inputs... You've actually found a real bug!

```sh
jq -r '[.[] | {name: .name, url: .url, language: .language, stargazers_count: .stargazers_count, watchers_count: .watchers_count}]
```

**Comment by yamafaktory** [comment]
@Th3Whit3Wolf thanks for the time you've spent adding more benchmarks and indirectly making me digging a bit more those timings :bow: ! The bug has been fixed now :tada: . A new version of `jql` has been released and this time proper benchmarks are available https://github.com/yamafaktory/jql/blob/master/PERFORMANCE.md!

**Comment by Th3Whit3Wolf** [comment]
That's awesome glad I could help!
