### ISSUE TITLE
Crash when piping to a pager like less, bat

### ISSUE THREAD

**Issue by bb** [yamafaktory/jql#86]
jql crashes for me when piping the output to a pager like less or bat and the output is not fully read (because it's longer than the viewport). I'm running version 2.9.3. installed via brew on macos (latest version).

This works as it only provides very few lines of output for my example file:
```
RUST_BACKTRACE=1 jql '.!'  tmp.json | less
```
However, when outputting a bit more, it crashes when I quit the pager without scrolling to the end:

```
RUST_BACKTRACE=1 jql '.'  tmp.json | less
thread 'main' panicked at 'failed printing to stdout: Broken pipe (os error 32)', library/std/src/io/stdio.rs:1021:9
stack backtrace:
   0: _rust_begin_unwind
   1: std::panicking::begin_panic_fmt
   2: jql::render_output
   3: <async_std::task::builder::SupportTaskLocals<F> as core::future::future::Future>::poll
   4: jql::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[1]    60860 abort      RUST_BACKTRACE=1 jql '.' tmp.json |
       60861 done       less
```

When I scroll the `less` to the end (e.g. by pressing `G` key) or when I pipe to `cat` which also reads everything, there's no issue.

Please let me know when you need more information.

**Comment by yamafaktory** [comment]
Hi @bb and thanks for reporting the issue.
So to recap, it works with `cat` but not with `less`, right?
Can you provide the failing JSON file?
I'll have a look at it anyway.

**Comment by bb** [comment]
Yes. Works with any consumer which reads to the end, e.g. cat. Fails with those who only read part of the output, e.g. less (assuming output is longer than screen height. Otherwise less reads all of it and it works).

**Comment by bb** [comment]
Just noticed I only answered one of the two question. I worked with geojson files from https://osm-boundaries.com/Map. But the actual file does not matter, as long as it's longer than the screen size and bigger than some internal buffer.

The geojson files need OSM login, but there here are two examples of (non-geojson) json data:

This fails:
`curl https://osm-boundaries.com/ajax.php\?cmd\=GetTreeContent\&db\=osm20201228\&rootId\=-2202162 | jql "." | less` (If you press `q` in less WITHOUT scrolling down. File size is 2700k.)

While this works:
`curl https://osm-boundaries.com/ajax.php\?cmd\=GetTreeContent\&db\=osm20201228\&rootId\=%23 | jql "." | less` (16k).

**Comment by yamafaktory** [comment]
Yeah, the problem is that jql reads the whole piped content in memory and expect it to be valid JSON. `less` - and by extension `bat` (which is using `less` by default https://github.com/sharkdp/bat#automatic-paging) - is paging the output which is thus incomplete JSON.
I might have to look at https://docs.rs/serde_json/1.0.62/serde_json/struct.StreamDeserializer.html.
Will keep you posted.

**Comment by yamafaktory** [comment]
@bb sorry for the late reply!

I was checking again and indeed `jql` is already using what I mentioned in the previous message. It seems to be a Rust issue in the end https://github.com/rust-lang/rust/issues/46016.

They mentioned multiple workarounds including this one used by `ripgrep` https://github.com/BurntSushi/ripgrep/pull/586/files.

Since it's using `unsafe`, I'd prefer to avoid it... but it might be the only solution currently available.

**Comment by bb** [comment]
@yamafaktory thanks for following up. No need to worry or feel sorry. Honestly, I finished the stuff I was using jql for and don't need it now or anytime soon. So it's absolutely not critical nor urgent for me...

My workaround was to press Shift-G in less so it scrolls to the end and thus prevents the crash.

**Comment by yerke** [comment]
You might want to try the approach similar to https://github.com/crev-dev/cargo-crev/commit/3f3dedf8428a054072492401a086c51c82a08215 (as discussed in https://github.com/crev-dev/cargo-crev/issues/287). No unsafe there.

**Comment by yamafaktory** [comment]
@yerke I guess this is what I mentioned a while ago here https://github.com/yamafaktory/jql/issues/86#issuecomment-780163462

**Comment by yamafaktory** [comment]
@yerke nevermind this was just one of the link, I see what you mean (commit).

**Comment by yamafaktory** [comment]
I'm going to release a new version soon, thanks @yerke!

Looking good now: https://asciinema.org/a/465294.

**Comment by yamafaktory** [comment]
@bb A new version has been released. Don't hesitate to re-open the issue if the fix doesn't work has expected (works for me locally and in the CI).
