### ISSUE TITLE
Windows build always gets 'Empty group' in all cases but `.`

### ISSUE THREAD

**Issue by cpkio** [yamafaktory/jql#96]
I've built latest with `cargo install jql`, but cannot get any result but full json printing with `.`. Spent an hour in Powershell & CMD.

**Comment by yamafaktory** [comment]
Hi @cpkio. `jql` is compiled against Window in the CI but there are specific tests for this OS and I'm a Window user at all... Can you please give an example (JSON file) and the command you're running?
