### ISSUE TITLE
Windows build always gets 'Empty group' in all cases but `.` (once again)

### ISSUE THREAD

**Issue by cpkio** [yamafaktory/jql#97]
#96 was closed prematurely. @yamafaktory you closed #96 and didn't notice `echo '{ "primes": [7, 11, 13] }' | jql '"primes"'` has been tested by me with same result. And what about CMD results? Powershell on Linux may behave differently. Please take a closer look.

**Comment by yamafaktory** [comment]
Maybe try what is suggested in this article https://devblogs.microsoft.com/scripting/weekend-scripter-understanding-quotation-marks-in-powershell/.

**Comment by yamafaktory** [comment]
Also https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_quoting_rules?view=powershell-7.1 and https://stackoverflow.com/questions/7760545/escape-double-quotes-in-parameter for CMD.
