### ISSUE TITLE
Option for validation

### ISSUE THREAD

**Issue by ktk** [yamafaktory/jql#98]
First, thanks for the tool, great to see a binary option for working with json that does not require a VM or anything alike!

I noticed there is no option to validate a JSON file without providing a selector. I often have the case that I have to work with files from somewhere else and often they are not even valid JSON so I either manually or in pipelines validate the file first.

Was there a discussion about a feature like this as well? Couldn't find one in the closed issues so far.

**Comment by yamafaktory** [comment]
Hi @ktk and thanks for the feedback 🙇!

This sounds like a good use case. I'll have a look at this and will keep you posted!
